// Fictional sample listings used to demo Parkly in Pune.
// Areas and landmarks are real places; the spaces, hosts and prices are made up
// and every listing is flagged `isDemo` so the app labels it as a demo.

const ALL_DAYS = [0, 1, 2, 3, 4, 5, 6];
const WEEKDAYS = [1, 2, 3, 4, 5];
const MON_SAT = [1, 2, 3, 4, 5, 6];

export const SCHEDULES = {
  allDay: { is24x7: true, days: ALL_DAYS, startTime: '00:00', endTime: '23:59' },
  longDay: { is24x7: false, days: ALL_DAYS, startTime: '07:00', endTime: '23:00' },
  officeHours: { is24x7: false, days: MON_SAT, startTime: '08:00', endTime: '20:00' },
  workday: { is24x7: false, days: WEEKDAYS, startTime: '09:00', endTime: '19:00' },
  evenings: { is24x7: false, days: ALL_DAYS, startTime: '18:00', endTime: '23:30' },
  weekends: { is24x7: false, days: [0, 6], startTime: '08:00', endTime: '22:00' },
};

// Demo hosts (fictional). Emails use the reserved .example domain so they can never be real inboxes.
export const DEMO_HOSTS = [
  { key: 'anjali', name: 'Anjali Patwardhan' },
  { key: 'rohan', name: 'Rohan Joshi' },
  { key: 'farhan', name: 'Farhan Shaikh' },
  { key: 'meera', name: 'Meera Kulkarni' },
  { key: 'vikram', name: 'Vikram Deshpande' },
].map((host) => ({ ...host, email: `${host.key}@demo.parkly.example` }));

/**
 * [dLat, dLng] offsets are small shifts from each area's centre point
 * (roughly 100 m – 1.5 km) so listings spread out realistically.
 */
export const DEMO_LISTINGS = [
  // Baner
  {
    host: 'anjali',
    area: 'Baner',
    offset: [0.0021, 0.0034],
    title: 'Covered society parking near Baner–Balewadi High Street',
    spaceType: 'society',
    vehicleSize: 'suv',
    pricePerHour: 40,
    amenities: ['covered', 'cctv', 'security_guard', 'gated'],
    line1: 'Sai Vihar Society, Lane 5, Baner Road',
    landmark: 'Near Balewadi High Street',
    schedule: 'officeHours',
    rules: ['Show your booking to the security guard at the gate', 'Park only in slot B-14'],
    description:
      'Basement slot in a gated society, a short walk from the cafés and restaurants of Balewadi High Street. Fits an SUV comfortably.',
  },
  {
    host: 'rohan',
    area: 'Baner',
    offset: [-0.0032, -0.0018],
    title: 'Private driveway off Baner Pashan Link Road',
    spaceType: 'driveway',
    vehicleSize: 'sedan',
    pricePerHour: 30,
    amenities: ['well_lit'],
    line1: 'Bungalow 12, Pancard Club Road, Baner',
    landmark: 'Opposite Mahabaleshwar Hotel',
    schedule: 'workday',
    rules: ['No overnight parking', 'Please do not block the gate'],
    description: 'Open driveway in front of an independent bungalow. Free on weekdays while we are at work.',
  },
  {
    host: 'vikram',
    area: 'Baner',
    offset: [0.0045, -0.0052],
    title: 'Office basement slot near Baner IT parks',
    spaceType: 'commercial',
    vehicleSize: 'suv',
    pricePerHour: 50,
    amenities: ['covered', 'cctv', 'security_guard', 'ev_charging', 'well_lit'],
    line1: 'Level B1, Business Bay, Baner',
    landmark: 'Near Symbiosis Institute, Baner',
    schedule: 'longDay',
    rules: ['EV charging billed separately by the building', 'Speed limit 10 km/h in basement'],
    description: 'Reserved basement bay in a commercial building with a 7 kW EV charger nearby.',
  },

  // Hinjawadi
  {
    host: 'rohan',
    area: 'Hinjawadi',
    offset: [0.0028, 0.0041],
    title: 'Covered parking near Hinjawadi Phase 1 Infotech Park',
    spaceType: 'society',
    vehicleSize: 'sedan',
    pricePerHour: 30,
    amenities: ['covered', 'cctv', 'gated'],
    line1: 'Megapolis Sunway, Phase 1, Hinjawadi',
    landmark: 'Near Wipro Circle',
    schedule: 'workday',
    rules: ['Enter via Gate 2', 'No car washing'],
    description: 'Ideal for a full office day in Phase 1. Covered slot inside a gated society.',
  },
  {
    host: 'meera',
    area: 'Hinjawadi',
    offset: [-0.0061, -0.0102],
    title: 'Open lot near Hinjawadi Phase 2',
    spaceType: 'open_lot',
    vehicleSize: 'suv',
    pricePerHour: 20,
    amenities: ['well_lit'],
    line1: 'Survey No. 21, Maan Road, Hinjawadi Phase 2',
    landmark: 'Near Infosys Phase 2 gate',
    schedule: 'officeHours',
    rules: ['Unpaved surface', 'Park at your own risk during heavy rain'],
    description: 'Large open plot with easy entry and exit. Budget-friendly all-day parking for Phase 2 offices.',
  },
  {
    host: 'vikram',
    area: 'Hinjawadi',
    offset: [0.0011, -0.0034],
    title: 'Secure 24×7 garage near Hinjawadi Chowk',
    spaceType: 'garage',
    vehicleSize: 'suv',
    pricePerHour: 45,
    amenities: ['covered', 'cctv', 'security_guard', 'gated', 'well_lit'],
    line1: 'Shop 4, Blue Ridge Road, Hinjawadi',
    landmark: 'Near Hinjawadi Chowk',
    schedule: 'allDay',
    rules: ['Keys stay with you', 'Call the host on arrival'],
    description: 'Lockable garage open round the clock — useful for night shifts.',
  },

  // Viman Nagar
  {
    host: 'farhan',
    area: 'Viman Nagar',
    offset: [0.0019, -0.0027],
    title: 'Society parking 5 minutes from Pune Airport',
    spaceType: 'society',
    vehicleSize: 'suv',
    pricePerHour: 50,
    amenities: ['covered', 'cctv', 'security_guard', 'gated'],
    line1: 'Clover Park, Lane 7, Viman Nagar',
    landmark: 'Near Pune International Airport',
    schedule: 'allDay',
    rules: ['Show booking at the gate', 'Maximum stay 24 hours'],
    description: 'Handy for airport pickups and short trips. Covered slot in a gated society.',
  },
  {
    host: 'anjali',
    area: 'Viman Nagar',
    offset: [-0.0025, 0.0041],
    title: 'Driveway near Phoenix Marketcity',
    spaceType: 'driveway',
    vehicleSize: 'sedan',
    pricePerHour: 60,
    amenities: ['cctv', 'well_lit'],
    line1: 'Row House 3, Nagar Road, Viman Nagar',
    landmark: 'Near Phoenix Marketcity',
    schedule: 'longDay',
    rules: ['No overnight parking'],
    description: 'Skip the mall parking queue — a private driveway a short walk from Phoenix Marketcity.',
  },
  {
    host: 'meera',
    area: 'Viman Nagar',
    offset: [0.0052, 0.0012],
    title: 'Weekend parking near Symbiosis, Viman Nagar',
    spaceType: 'commercial',
    vehicleSize: 'sedan',
    pricePerHour: 35,
    amenities: ['covered', 'security_guard'],
    line1: 'Office complex, Datta Mandir Chowk, Viman Nagar',
    landmark: 'Near Symbiosis College',
    schedule: 'weekends',
    rules: ['Weekends only', 'Entry from the rear gate'],
    description: 'Office parking that sits empty on weekends. Covered and guarded.',
  },

  // Koregaon Park
  {
    host: 'farhan',
    area: 'Koregaon Park',
    offset: [0.0014, 0.0023],
    title: 'Bungalow driveway on North Main Road',
    spaceType: 'driveway',
    vehicleSize: 'suv',
    pricePerHour: 70,
    amenities: ['gated', 'well_lit', 'cctv'],
    line1: 'Lane 6, North Main Road, Koregaon Park',
    landmark: 'Near German Bakery',
    schedule: 'longDay',
    rules: ['Please keep noise low after 10 pm', 'No overnight parking'],
    description: 'Gated driveway on a quiet lane off North Main Road — close to KP’s restaurants.',
  },
  {
    host: 'vikram',
    area: 'Koregaon Park',
    offset: [-0.0031, -0.0015],
    title: 'Evening parking near KP restaurants',
    spaceType: 'commercial',
    vehicleSize: 'sedan',
    pricePerHour: 60,
    amenities: ['security_guard', 'well_lit'],
    line1: 'Office forecourt, Lane 5, Koregaon Park',
    landmark: 'Near Osho Teerth Park',
    schedule: 'evenings',
    rules: ['Available after office hours only', 'Leave by 11:30 pm'],
    description: 'An office forecourt that opens up in the evenings — perfect for dinner plans.',
  },
  {
    host: 'meera',
    area: 'Koregaon Park',
    offset: [0.0038, -0.0042],
    title: 'Covered garage near Koregaon Park Plaza',
    spaceType: 'garage',
    vehicleSize: 'suv',
    pricePerHour: 80,
    amenities: ['covered', 'cctv', 'gated', 'ev_charging'],
    line1: 'Garage 2, Boat Club Road',
    landmark: 'Near Koregaon Park Plaza',
    schedule: 'allDay',
    rules: ['Call on arrival to open the shutter'],
    description: 'Private covered garage with a charging point. Available 24×7.',
  },

  // Kalyani Nagar
  {
    host: 'anjali',
    area: 'Kalyani Nagar',
    offset: [0.0017, 0.0024],
    title: 'Society slot near Central Avenue',
    spaceType: 'society',
    vehicleSize: 'sedan',
    pricePerHour: 50,
    amenities: ['covered', 'cctv', 'gated'],
    line1: 'Marigold Society, Central Avenue, Kalyani Nagar',
    landmark: 'Near Central Avenue',
    schedule: 'officeHours',
    rules: ['Park only in slot 22'],
    description: 'Covered slot in a quiet society close to Kalyani Nagar’s cafés and offices.',
  },
  {
    host: 'farhan',
    area: 'Kalyani Nagar',
    offset: [-0.0029, 0.0011],
    title: 'Business park parking near Kalyani Nagar',
    spaceType: 'commercial',
    vehicleSize: 'suv',
    pricePerHour: 55,
    amenities: ['covered', 'cctv', 'security_guard', 'ev_charging', 'well_lit'],
    line1: 'Basement 2, Nagar Road, Kalyani Nagar',
    landmark: 'Near Commerzone IT Park',
    schedule: 'workday',
    rules: ['Show booking at the boom barrier'],
    description: 'Reserved basement parking in a business park with EV charging.',
  },
  {
    host: 'rohan',
    area: 'Kalyani Nagar',
    offset: [0.0036, -0.0033],
    title: 'Open driveway near Kalyani Nagar Jogging Park',
    spaceType: 'driveway',
    vehicleSize: 'hatchback',
    pricePerHour: 35,
    amenities: ['well_lit'],
    line1: 'Bungalow 8, Lane 3, Kalyani Nagar',
    landmark: 'Near Jogging Park',
    schedule: 'longDay',
    rules: ['Suitable for hatchbacks only', 'No overnight parking'],
    description: 'Compact driveway best suited to small cars.',
  },

  // Shivajinagar
  {
    host: 'meera',
    area: 'Shivajinagar',
    offset: [0.0022, -0.0014],
    title: 'Parking near FC Road and Fergusson College',
    spaceType: 'society',
    vehicleSize: 'sedan',
    pricePerHour: 40,
    amenities: ['gated', 'cctv'],
    line1: 'Shree Apartments, Model Colony',
    landmark: 'Near Fergusson College Road',
    schedule: 'officeHours',
    rules: ['Enter slowly — narrow gate'],
    description: 'Gated society parking a few minutes from FC Road shopping.',
  },
  {
    host: 'vikram',
    area: 'Shivajinagar',
    offset: [-0.0018, 0.0026],
    title: 'Covered parking near Shivajinagar District Court',
    spaceType: 'commercial',
    vehicleSize: 'suv',
    pricePerHour: 45,
    amenities: ['covered', 'security_guard', 'cctv'],
    line1: 'Commercial complex, Wakdewadi, Shivajinagar',
    landmark: 'Near District Court',
    schedule: 'workday',
    rules: ['Weekdays only'],
    description: 'Save time on court and office days with a covered, guarded slot.',
  },
  {
    host: 'anjali',
    area: 'Shivajinagar',
    offset: [0.0041, 0.0037],
    title: 'Garage near JM Road',
    spaceType: 'garage',
    vehicleSize: 'sedan',
    pricePerHour: 50,
    amenities: ['covered', 'gated'],
    line1: 'Garage 1, Ghole Road, Shivajinagar',
    landmark: 'Near JM Road',
    schedule: 'longDay',
    rules: ['Close the shutter after parking'],
    description: 'Private garage within walking distance of JM Road.',
  },

  // Wakad
  {
    host: 'rohan',
    area: 'Wakad',
    offset: [0.0024, 0.0031],
    title: 'Society parking off Mumbai–Bengaluru Highway',
    spaceType: 'society',
    vehicleSize: 'suv',
    pricePerHour: 30,
    amenities: ['covered', 'cctv', 'security_guard', 'gated'],
    line1: 'Palash Society, Wakad Road',
    landmark: 'Near Wakad Bridge',
    schedule: 'allDay',
    rules: ['Show booking at the gate'],
    description: 'Covered, guarded parking with quick highway access. Open 24×7.',
  },
  {
    host: 'meera',
    area: 'Wakad',
    offset: [-0.0037, -0.0022],
    title: 'Open plot near Dange Chowk',
    spaceType: 'open_lot',
    vehicleSize: 'suv',
    pricePerHour: 20,
    amenities: [],
    line1: 'Plot 14, Thergaon Road, Wakad',
    landmark: 'Near Dange Chowk',
    schedule: 'longDay',
    rules: ['Unpaved surface'],
    description: 'Simple, affordable open-plot parking near Dange Chowk.',
  },
  {
    host: 'farhan',
    area: 'Wakad',
    offset: [0.0009, -0.0048],
    title: 'Driveway near Phoenix Mall of the Millennium',
    spaceType: 'driveway',
    vehicleSize: 'sedan',
    pricePerHour: 35,
    amenities: ['well_lit', 'cctv'],
    line1: 'Row House 21, Kaspate Wasti, Wakad',
    landmark: 'Near Phoenix Mall of the Millennium',
    schedule: 'weekends',
    rules: ['Weekends only'],
    description: 'Weekend driveway parking close to the mall.',
  },

  // Aundh
  {
    host: 'vikram',
    area: 'Aundh',
    offset: [0.0016, 0.0027],
    title: 'Covered parking near ITI Road',
    spaceType: 'society',
    vehicleSize: 'sedan',
    pricePerHour: 40,
    amenities: ['covered', 'gated', 'cctv'],
    line1: 'Aundh Heights, ITI Road',
    landmark: 'Near ITI Road shops',
    schedule: 'officeHours',
    rules: ['Park only in slot A-7'],
    description: 'Covered slot close to ITI Road shopping and restaurants.',
  },
  {
    host: 'anjali',
    area: 'Aundh',
    offset: [-0.0027, -0.0031],
    title: 'Driveway near DP Road',
    spaceType: 'driveway',
    vehicleSize: 'suv',
    pricePerHour: 35,
    amenities: ['well_lit'],
    line1: 'Bungalow 5, DP Road, Aundh',
    landmark: 'Near DP Road',
    schedule: 'workday',
    rules: ['No overnight parking'],
    description: 'Wide driveway suitable for SUVs.',
  },
  {
    host: 'rohan',
    area: 'Aundh',
    offset: [0.0043, -0.0009],
    title: 'EV-ready garage near Westend Mall',
    spaceType: 'garage',
    vehicleSize: 'suv',
    pricePerHour: 55,
    amenities: ['covered', 'cctv', 'ev_charging', 'gated'],
    line1: 'Garage 3, Parihar Chowk, Aundh',
    landmark: 'Near Westend Mall',
    schedule: 'longDay',
    rules: ['Bring your own EV charging cable'],
    description: 'Private garage with a 15A socket for EV charging.',
  },

  // Kothrud
  {
    host: 'meera',
    area: 'Kothrud',
    offset: [0.0021, 0.0019],
    title: 'Society parking near Karve Road',
    spaceType: 'society',
    vehicleSize: 'sedan',
    pricePerHour: 35,
    amenities: ['gated', 'security_guard'],
    line1: 'Shantiban Society, Karve Road',
    landmark: 'Near Karishma Chowk',
    schedule: 'officeHours',
    rules: ['Show booking at the gate'],
    description: 'Gated society parking close to Karve Road offices and shops.',
  },
  {
    host: 'farhan',
    area: 'Kothrud',
    offset: [-0.0034, -0.0026],
    title: 'Open lot near MIT World Peace University',
    spaceType: 'open_lot',
    vehicleSize: 'suv',
    pricePerHour: 25,
    amenities: ['well_lit'],
    line1: 'Survey No. 124, Paud Road, Kothrud',
    landmark: 'Near MIT-WPU',
    schedule: 'longDay',
    rules: ['Unpaved surface'],
    description: 'Affordable open parking near the university campus.',
  },
  {
    host: 'vikram',
    area: 'Kothrud',
    offset: [0.0039, -0.0041],
    title: 'Covered parking near Kothrud Depot',
    spaceType: 'commercial',
    vehicleSize: 'sedan',
    pricePerHour: 40,
    amenities: ['covered', 'cctv', 'security_guard'],
    line1: 'Shopping complex, Paud Road, Kothrud',
    landmark: 'Near Kothrud Depot',
    schedule: 'allDay',
    rules: ['Keep your parking ticket visible'],
    description: 'Covered commercial parking, open round the clock.',
  },

  // Hadapsar
  {
    host: 'rohan',
    area: 'Hadapsar',
    offset: [0.0026, 0.0033],
    title: 'Parking near Magarpatta City',
    spaceType: 'society',
    vehicleSize: 'suv',
    pricePerHour: 30,
    amenities: ['covered', 'cctv', 'gated', 'security_guard'],
    line1: 'Cosmos Society, Magarpatta Road, Hadapsar',
    landmark: 'Near Magarpatta City',
    schedule: 'workday',
    rules: ['Enter via the service gate'],
    description: 'Covered parking a short walk from the Magarpatta City offices.',
  },
  {
    host: 'anjali',
    area: 'Hadapsar',
    offset: [-0.0021, 0.0047],
    title: 'Driveway near Amanora Mall',
    spaceType: 'driveway',
    vehicleSize: 'sedan',
    pricePerHour: 30,
    amenities: ['well_lit'],
    line1: 'Row House 9, Amanora Road, Hadapsar',
    landmark: 'Near Amanora Mall',
    schedule: 'longDay',
    rules: ['No overnight parking'],
    description: 'Private driveway near Amanora Town Centre.',
  },
  {
    host: 'farhan',
    area: 'Hadapsar',
    offset: [0.0047, -0.0019],
    title: '24×7 open lot near Hadapsar Gadital',
    spaceType: 'open_lot',
    vehicleSize: 'suv',
    pricePerHour: 20,
    amenities: ['security_guard', 'well_lit'],
    line1: 'Plot 7, Solapur Road, Hadapsar',
    landmark: 'Near Hadapsar Gadital',
    schedule: 'allDay',
    rules: ['Security guard on site at night'],
    description: 'Guarded open lot on Solapur Road, available 24×7.',
  },
];
